"""topoqaoa -- Topology-Guided Graph RL for QAOA Warm Starts.

CPU reference implementation. Every public number this package reports is
generated by running the code (see scripts/ and the Makefile); nothing is
hard-coded. QAOA is evaluated with an exact statevector simulator and an
analytic depth-1 formula, both in numpy.
"""
from __future__ import annotations

__version__ = "0.1.0"

from . import (  # noqa: F401
    audit,
    baselines,
    config,
    descriptors,
    env,
    graph_generators,
    maxcut_exact,
    metrics,
    qaoa,
    seed,
    splits,
)
