#!/usr/bin/env python
"""Generate LaTeX tables and a macro file from results/summary.json.

Writes, under results/:
  macros.tex        -- \\newcommand for every scalar the manuscript cites
  tab_main.tex      -- per-policy table at the headline depth (tabular body)
  tab_depth.tex     -- advantage-vs-depth table (tabular body)
  tab_family.tex    -- per-family held-out ratios at the headline depth
  tab_frontier.tex  -- query-budget frontier at selected query indices
  main_results.tex  -- kept as an alias of tab_main.tex for backwards compat.

The manuscript \\input's these, so no number is ever transcribed by hand.
"""
import json
from pathlib import Path

import _bootstrap  # noqa: F401

ROMAN = {1: "I", 2: "II", 3: "III", 4: "IV", 5: "V"}
POLICIES = ["random", "spectral", "topology", "graph_conditioned", "stk"]
PRETTY = {
    "random": "Random",
    "spectral": "Spectral ramp",
    "topology": "Topology ramp",
    "graph_conditioned": "Descriptor mean",
    "stk": "STK transfer (ours)",
}
MAC = {
    "random": "Random",
    "spectral": "Spectral",
    "topology": "Topology",
    "graph_conditioned": "Gc",
    "stk": "Stk",
}


def f4(x):
    return f"{x:.4f}"


def main() -> None:
    s = json.loads(Path("results/summary.json").read_text())
    out = Path("results")
    out.mkdir(exist_ok=True)
    depths = [int(p) for p in s["depths"]]
    hd = int(s["headline_depth"])
    bd = s["by_depth"]
    adv = {r["p"]: r for r in s["advantage_vs_depth"]}

    # ---------------- macros.tex ----------------
    m = [r"% Auto-generated by scripts/make_tables.py -- do not edit by hand."]

    def cmd(name, val):
        m.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    cmd("Ngraphs", s["headline"]["n_graphs"])
    cmd("Nfamilies", len(s["config"]["families"]))
    cmd("budgetval", s["config"]["budget"])
    cmd("seedval", s["config"]["seed"])
    cmd("Ndepths", len(depths))
    cmd("headlinedepth", hd)
    cmd("stkr", s["config"]["stk_r"])
    cmd("sizesval", ",".join(str(x) for x in s["config"]["sizes"]))
    prov = s["provenance"]
    cmd("runtimeval", prov.get("runtime_sec", 0.0))
    cmd("peakmem", round(prov.get("peak_memory_mb", 0.0), 1))
    cmd("leakageclean", "true" if s["leakage_clean"] else "false")
    for lib in ("python", "numpy", "scipy", "networkx", "sklearn", "matplotlib"):
        cmd("ver" + lib.capitalize(), prov.get("versions", {}).get(lib, "NA"))

    for p in depths:
        R = ROMAN[p]
        pol = bd[str(p)]["policies"]
        for k in POLICIES:
            cmd(f"fr{MAC[k]}P{R}", f4(pol[k]["approx_ratio"]["mean"]))
            cmd(f"ci{MAC[k]}P{R}", f4(pol[k]["approx_ratio"]["ci95"]))
            cmd(f"fq{MAC[k]}P{R}", f4(pol[k]["first_query_ratio"]))
        cmd(f"oracleP{R}", f4(bd[str(p)]["oracle_ratio_mean"]))
        a = adv[p]
        cmd(f"deltaStkRampP{R}", f"{a['delta_stk_vs_best_ramp']:+.4f}")
        cmd(f"ciDeltaStkRampP{R}", f4(a["delta_best_ramp_ci95"]))
        cmd(f"deltaStkRampFqP{R}", f"{a['delta_stk_vs_best_ramp_first_query']:+.4f}")
        cmd(f"deltaStkSpecP{R}", f"{a['delta_stk_vs_spectral']:+.4f}")
        cmd(f"sigStkRampP{R}", "yes" if a["significant_positive"] else "no")
        # graph_conditioned (averaging) shortfall vs best ramp, for the cautionary point
        gc = pol["graph_conditioned"]["approx_ratio"]["mean"]
        ramp = max(pol["spectral"]["approx_ratio"]["mean"],
                   pol["topology"]["approx_ratio"]["mean"])
        cmd(f"deltaGcRampP{R}", f"{gc - ramp:+.4f}")
    (out / "macros.tex").write_text("\n".join(m) + "\n")

    # ---------------- tab_main.tex (headline depth) ----------------
    pol = bd[str(hd)]["policies"]
    best_final = max(pol[k]["approx_ratio"]["mean"] for k in POLICIES)
    rows = [r"\begin{tabular}{lcccc}", r"\toprule",
            r"Policy & Approx.\ ratio (final) & One-shot ($q{=}1$) & "
            r"Queries$\to$target & Hit rate \\", r"\midrule"]
    for k in POLICIES:
        a = pol[k]["approx_ratio"]
        final = a["mean"]
        cell = (rf"$\mathbf{{{final:.4f}}}\pm{a['ci95']:.4f}$"
                if abs(final - best_final) < 1e-9
                else rf"${final:.4f}\pm{a['ci95']:.4f}$")
        rows.append(
            f"{PRETTY[k]} & {cell} & ${pol[k]['first_query_ratio']:.4f}$ & "
            f"${pol[k]['queries_to_target_mean']:.2f}$ & "
            f"${pol[k]['target_hit_rate']:.2f}$ \\\\")
    rows += [r"\bottomrule", r"\end{tabular}"]
    (out / "tab_main.tex").write_text("\n".join(rows) + "\n")
    (out / "main_results.tex").write_text("\n".join(rows) + "\n")

    # ---------------- tab_depth.tex ----------------
    d = [r"\begin{tabular}{lcccccc}", r"\toprule",
         r"$p$ & Best ramp & Descriptor mean & STK (ours) & Oracle "
         r"& $\Delta_{\mathrm{final}}$ & $\Delta_{\text{one-shot}}$ \\",
         r"\midrule"]
    for p in depths:
        a = adv[p]
        ramp = max(a["spectral_mean"], a["topology_mean"])
        stk = a["stk_mean"]
        stk_cell = rf"$\mathbf{{{stk:.4f}}}$" if stk >= ramp else f"${stk:.4f}$"
        d.append(
            f"${p}$ & ${ramp:.4f}$ & ${a['graph_conditioned_mean']:.4f}$ & {stk_cell} & "
            f"${a['oracle_mean']:.4f}$ & "
            f"${a['delta_stk_vs_best_ramp']:+.4f}\\pm{a['delta_best_ramp_ci95']:.4f}$ & "
            f"${a['delta_stk_vs_best_ramp_first_query']:+.4f}$ \\\\")
    d += [r"\bottomrule", r"\end{tabular}"]
    (out / "tab_depth.tex").write_text("\n".join(d) + "\n")

    # ---------------- tab_family.tex (headline depth) ----------------
    byf = bd[str(hd)]["by_family"]
    fams = sorted(byf.keys())
    famlabel = {
        "erdos_renyi": "Erd\\H{o}s--R\\'enyi", "regular": "Random regular",
        "barabasi_albert": "Barab\\'asi--Albert", "watts_strogatz": "Watts--Strogatz",
        "grid": "2-D grid", "stochastic_block": "Stochastic block",
    }
    fl = [r"\setlength{\tabcolsep}{4pt}", r"\begin{tabular}{lccccc}", r"\toprule",
          r"Family & Random & Spectral & Topology & Descr.\ mean & STK (ours) \\",
          r"\midrule"]
    for fam in fams:
        cells = []
        best = max(byf[fam].get(k, {}).get("mean", 0.0) for k in POLICIES)
        for k in POLICIES:
            mm = byf[fam].get(k, {})
            v, c = mm.get("mean", 0.0), mm.get("ci95", 0.0)
            cells.append(rf"$\mathbf{{{v:.4f}}}\pm{c:.4f}$" if abs(v - best) < 1e-9
                         else rf"${v:.4f}\pm{c:.4f}$")
        fl.append(f"{famlabel_get(famlabel, fam)} & " + " & ".join(cells) + r" \\")
    fl += [r"\bottomrule", r"\end{tabular}"]
    (out / "tab_family.tex").write_text("\n".join(fl) + "\n")

    # ---------------- tab_frontier.tex (headline depth) ----------------
    fr = bd[str(hd)]["frontier"]
    budget = s["config"]["budget"]
    qidx = [q for q in (1, 2, 4, 8, 16, budget) if q <= budget]
    qidx = sorted(set(qidx))
    header = " & ".join([r"Policy"] + [f"$q{{=}}{q}$" for q in qidx])
    ft = [r"\begin{tabular}{l" + "c" * len(qidx) + "}", r"\toprule",
          header + r" \\", r"\midrule"]
    for k in POLICIES:
        curve = {pt[0]: pt[1] for pt in fr[k]}
        vals = " & ".join(f"${curve.get(q, curve[max(curve)]):.4f}$" for q in qidx)
        ft.append(f"{PRETTY[k]} & {vals} \\\\")
    ft += [r"\bottomrule", r"\end{tabular}"]
    (out / "tab_frontier.tex").write_text("\n".join(ft) + "\n")

    print("wrote results/macros.tex, tab_main.tex, tab_depth.tex, "
          "tab_family.tex, tab_frontier.tex")


def famlabel_get(d, fam):
    return d.get(fam, fam.replace("_", " "))


if __name__ == "__main__":
    main()
